"""
PDF Report Generator — Full 10–13 page PDF using fpdf2.
"""
from __future__ import annotations
import io
from datetime import date

try:
    from fpdf import FPDF
    HAS_FPDF = True
except ImportError:
    HAS_FPDF = False

COLORS = {
    "primary": (99, 102, 241),
    "success": (34, 197, 94),
    "warning": (249, 115, 22),
    "danger": (239, 68, 68),
    "dark": (17, 24, 39),
    "muted": (107, 114, 128),
    "light_bg": (248, 250, 252),
    "white": (255, 255, 255),
}


class PDFReportGenerator:
    """Generates a comprehensive PDF gap analysis report using fpdf2."""

    def generate(
        self,
        analysis: dict,
        roadmap: str,
        user_name: str,
        role_title: str,
    ) -> bytes:
        """
        Generate a 10–13 page PDF report.

        Returns:
            PDF as bytes.
        """
        if not HAS_FPDF:
            return b"%PDF-1.4\n% fpdf2 not installed"

        pdf = ResumePDF()
        pdf.set_auto_page_break(auto=True, margin=20)
        pdf.set_margins(20, 20, 20)

        # Page 1: Cover
        pdf.add_page()
        pdf.cover_page(user_name, role_title, analysis)

        # Page 2: Executive Summary
        pdf.add_page()
        pdf.section_header("Executive Summary")
        pdf.exec_summary(analysis)

        # Page 3: Skill Match Overview
        pdf.add_page()
        pdf.section_header("Skill Match Overview")
        pdf.skill_match_table(analysis)

        # Page 4: ATS Score
        pdf.add_page()
        pdf.section_header("ATS Compatibility Report")
        pdf.ats_report(analysis.get("ats", {}))

        # Page 5: Resume Section Scores
        pdf.add_page()
        pdf.section_header("Resume Quality Scores")
        pdf.section_scores(analysis.get("section_scores", {}))

        # Page 6-7: Gap Analysis Table
        pdf.add_page()
        pdf.section_header("Detailed Gap Analysis")
        pdf.gap_table(analysis)

        # Page 8-10: Roadmap
        pdf.add_page()
        pdf.section_header("30-Day Study Roadmap")
        pdf.roadmap_section(roadmap)

        # Page 11: Salary Estimate
        pdf.add_page()
        pdf.section_header("Salary Estimate")
        pdf.salary_section(analysis.get("salary", {}), role_title)

        # Page 12: Course Recommendations
        pdf.add_page()
        pdf.section_header("Top Recommended Courses")
        pdf.course_recommendations(analysis.get("retrieved_courses", {}))

        # Page 13: Next Steps
        pdf.add_page()
        pdf.section_header("Your Next Steps")
        pdf.next_steps(analysis)

        return bytes(pdf.output())


def _clean_str(text: str) -> str:
    if not isinstance(text, str):
        return str(text)
    replacements = {
        "—": "-", "–": "-", "•": "*", "▶": ">", "💡": "Tip: ",
        "✅": "[OK]", "❌": "[X]", "🎯": "*", "🚀": "!", "📊": "*",
        "📝": "*", "💰": "*", "👥": "*", "📤": "*", "🛠️": "*", "🏁": "*"
    }
    for k, v in replacements.items():
        text = text.replace(k, v)
    return text.encode("latin-1", errors="replace").decode("latin-1")


class ResumePDF(FPDF):

    def cell(self, *args, **kwargs):
        if len(args) >= 3 and isinstance(args[2], str):
            args = list(args)
            args[2] = _clean_str(args[2])
        elif "txt" in kwargs and isinstance(kwargs["txt"], str):
            kwargs["txt"] = _clean_str(kwargs["txt"])
        elif "text" in kwargs and isinstance(kwargs["text"], str):
            kwargs["text"] = _clean_str(kwargs["text"])
        return super().cell(*args, **kwargs)

    def multi_cell(self, *args, **kwargs):
        if len(args) >= 3 and isinstance(args[2], str):
            args = list(args)
            args[2] = _clean_str(args[2])
        elif "txt" in kwargs and isinstance(kwargs["txt"], str):
            kwargs["txt"] = _clean_str(kwargs["txt"])
        elif "text" in kwargs and isinstance(kwargs["text"], str):
            kwargs["text"] = _clean_str(kwargs["text"])
        return super().multi_cell(*args, **kwargs)


    def header(self):
        if self.page_no() > 1:
            self.set_fill_color(*COLORS["primary"])
            self.rect(0, 0, 210, 10, "F")
            self.set_font("Helvetica", "B", 8)
            self.set_text_color(*COLORS["white"])
            self.set_xy(10, 2)
            self.cell(0, 6, "Resume Gap Pro  •  AI-Powered Career Analysis", ln=False)
            self.set_xy(0, 2)
            self.cell(200, 6, f"Page {self.page_no()}", align="R", ln=False)
            self.set_text_color(0, 0, 0)
            self.ln(12)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(*COLORS["muted"])
        self.cell(0, 5, "Generated by Resume Gap Pro  •  For personal use only", align="C")

    def section_header(self, title: str):
        self.set_fill_color(*COLORS["primary"])
        self.set_text_color(*COLORS["white"])
        self.set_font("Helvetica", "B", 14)
        self.cell(0, 12, f"  {title}", fill=True, ln=True)
        self.set_text_color(0, 0, 0)
        self.ln(4)

    def cover_page(self, name: str, role_title: str, analysis: dict):
        # Header block
        self.set_fill_color(*COLORS["dark"])
        self.rect(0, 0, 210, 80, "F")

        self.set_text_color(*COLORS["white"])
        self.set_font("Helvetica", "B", 28)
        self.set_xy(15, 18)
        self.cell(0, 12, "Resume Gap Analysis", ln=True)

        self.set_font("Helvetica", "", 16)
        self.set_xy(15, 36)
        self.cell(0, 8, f"Candidate: {name or 'Anonymous'}", ln=True)

        self.set_xy(15, 50)
        self.cell(0, 8, f"Target Role: {role_title}", ln=True)

        self.set_font("Helvetica", "I", 12)
        self.set_xy(15, 65)
        self.cell(0, 6, f"Generated: {date.today().strftime('%d %B %Y')}", ln=True)

        # Score badge
        self.set_text_color(0, 0, 0)
        score = analysis.get("match_score", 0)
        score_color = COLORS["success"] if score >= 70 else COLORS["warning"] if score >= 40 else COLORS["danger"]
        self.set_fill_color(*score_color)
        self.set_xy(140, 90)
        self.set_text_color(*COLORS["white"])
        self.set_font("Helvetica", "B", 36)
        self.cell(55, 20, f"{int(score)}%", align="C", fill=True, ln=True)
        self.set_text_color(*COLORS["muted"])
        self.set_font("Helvetica", "", 11)
        self.set_xy(140, 112)
        self.cell(55, 6, "Match Score", align="C", ln=True)

        # Tagline
        self.set_text_color(0, 0, 0)
        self.set_xy(15, 95)
        self.set_font("Helvetica", "B", 16)
        self.cell(110, 10, "Your AI-Powered Gap Report", ln=True)
        self.set_font("Helvetica", "", 12)
        self.set_xy(15, 110)
        self.multi_cell(115, 7,
            "This report identifies skill gaps, provides a personalised roadmap, "
            "ATS score, salary estimate, and peer comparison — all in one place.")

        # Key stats row
        self.set_xy(15, 160)
        stats = [
            ("Critical Gaps", len(analysis.get("critical_gaps", []))),
            ("Matched Skills", len(analysis.get("matched_skills", []))),
            ("ATS Score", f"{analysis.get('ats', {}).get('ats_score', 0)}/100"),
            ("Salary Boost", "Possible"),
        ]
        for label, val in stats:
            self.set_fill_color(*COLORS["light_bg"])
            self.cell(42, 24, "", border=1, fill=True)
            self.set_xy(self.get_x() - 42, self.get_y() + 2)
            self.set_font("Helvetica", "B", 16)
            self.set_text_color(*COLORS["primary"])
            self.cell(42, 8, str(val), align="C", ln=False)
            self.set_xy(self.get_x() - 42, self.get_y() + 10)
            self.set_font("Helvetica", "", 9)
            self.set_text_color(*COLORS["muted"])
            self.cell(42, 6, label, align="C", ln=False)
            self.set_xy(self.get_x(), 160)

    def exec_summary(self, analysis: dict):
        score = analysis.get("match_score", 0)
        gaps = analysis.get("critical_gaps", [])
        matched = analysis.get("matched_skills", [])

        findings = [
            f"Match Score: {int(score)}% — {'Strong' if score >= 70 else 'Moderate' if score >= 40 else 'Needs work'} alignment with the target role.",
            f"Critical Gaps Identified: {len(gaps)} skill(s) need immediate attention: {', '.join(gaps[:4]) or 'None'}.",
            f"Matched Skills: {len(matched)} skill(s) align with the JD including: {', '.join(matched[:5]) or 'None'}.",
        ]
        for i, f in enumerate(findings, 1):
            self.set_font("Helvetica", "B", 12)
            self.set_text_color(*COLORS["primary"])
            self.cell(8, 8, f"{i}.", ln=False)
            self.set_font("Helvetica", "", 11)
            self.set_text_color(0, 0, 0)
            self.multi_cell(0, 7, f)
            self.ln(2)

        tip = analysis.get("company_tip", "")
        if tip:
            self.set_fill_color(*COLORS["light_bg"])
            self.set_font("Helvetica", "I", 10)
            self.multi_cell(0, 7, f"💡 Company Tip: {tip}", fill=True)

    def skill_match_table(self, analysis: dict):
        headers = ["Skill", "Status", "Type"]
        col_w = [90, 50, 50]
        matched = analysis.get("matched_skills", [])
        gaps = analysis.get("critical_gaps", [])

        # Header row
        self.set_fill_color(*COLORS["primary"])
        self.set_text_color(*COLORS["white"])
        self.set_font("Helvetica", "B", 10)
        for h, w in zip(headers, col_w):
            self.cell(w, 9, h, border=1, fill=True)
        self.ln()
        self.set_text_color(0, 0, 0)

        rows = [(s, "✅ Matched", "Technical") for s in matched[:10]] + \
               [(s, "❌ Gap", "Critical") for s in gaps[:10]]
        for i, (skill, status, stype) in enumerate(rows):
            self.set_fill_color(248, 250, 252) if i % 2 == 0 else self.set_fill_color(255, 255, 255)
            color = COLORS["success"] if "Matched" in status else COLORS["danger"]
            self.set_font("Helvetica", "", 10)
            self.cell(col_w[0], 8, skill.title(), border=1, fill=True)
            self.set_text_color(*color)
            self.cell(col_w[1], 8, status, border=1, fill=True)
            self.set_text_color(0, 0, 0)
            self.cell(col_w[2], 8, stype, border=1, fill=True)
            self.ln()

    def ats_report(self, ats: dict):
        ats_score = ats.get("ats_score", 0)
        self.set_font("Helvetica", "B", 24)
        color = COLORS["success"] if ats_score >= 70 else COLORS["warning"] if ats_score >= 50 else COLORS["danger"]
        self.set_text_color(*color)
        self.cell(0, 12, f"ATS Score: {ats_score}/100", ln=True)
        self.set_text_color(0, 0, 0)
        self.ln(2)

        sub_scores = {
            "Keyword Match": ats.get("keyword_score", 0),
            "Formatting": ats.get("format_score", 0),
            "Section Structure": ats.get("section_score", 0),
            "Action Verbs & Metrics": ats.get("action_verb_score", 0),
        }
        for label, val in sub_scores.items():
            self.set_font("Helvetica", "B", 10)
            self.cell(80, 7, label, ln=False)
            self.set_font("Helvetica", "", 10)
            self.cell(20, 7, str(val), ln=True)

        self.ln(4)
        missing = ats.get("missing_keywords", [])
        if missing:
            self.set_font("Helvetica", "B", 11)
            self.cell(0, 8, "Missing Keywords (add to your resume):", ln=True)
            self.set_font("Helvetica", "", 10)
            self.multi_cell(0, 7, ", ".join(missing[:20]))
            self.ln(4)

        recs = ats.get("recommendations", [])
        if recs:
            self.set_font("Helvetica", "B", 11)
            self.cell(0, 8, "Recommendations:", ln=True)
            self.set_font("Helvetica", "", 10)
            for rec in recs:
                self.multi_cell(0, 7, f"• {rec}")
            self.ln(2)

    def section_scores(self, scores: dict):
        for section in ["summary", "experience", "skills", "projects"]:
            data = scores.get(section, {"score": 0, "feedback": ""})
            score = data.get("score", 0)
            feedback = data.get("feedback", "")
            color = COLORS["success"] if score >= 70 else COLORS["warning"] if score >= 50 else COLORS["danger"]
            self.set_font("Helvetica", "B", 12)
            self.set_text_color(*color)
            self.cell(0, 8, f"{section.title()}: {score}/100", ln=True)
            self.set_text_color(0, 0, 0)
            self.set_font("Helvetica", "", 10)
            self.multi_cell(0, 7, feedback)
            self.ln(4)

        overall = scores.get("overall", 0)
        grade = scores.get("grade", "C")
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(*COLORS["primary"])
        self.cell(0, 10, f"Overall Resume Score: {overall}/100  |  Grade: {grade}", ln=True)
        self.set_text_color(0, 0, 0)

    def gap_table(self, analysis: dict):
        gaps = analysis.get("critical_gaps", [])
        severity = analysis.get("severity", {})
        retrieved = analysis.get("retrieved_courses", {})

        headers = ["Skill", "Severity", "Top Course", "Platform"]
        col_w = [50, 30, 70, 40]

        self.set_fill_color(*COLORS["primary"])
        self.set_text_color(*COLORS["white"])
        self.set_font("Helvetica", "B", 9)
        for h, w in zip(headers, col_w):
            self.cell(w, 8, h, border=1, fill=True)
        self.ln()
        self.set_text_color(0, 0, 0)

        for i, gap in enumerate(gaps[:20]):
            sev = severity.get(gap, "Medium")
            courses = retrieved.get(gap, [])
            course_name = courses[0].get("course_name", "Search online")[:35] if courses else "Search online"
            platform = courses[0].get("platform", "-") if courses else "-"

            self.set_fill_color(248, 250, 252) if i % 2 == 0 else self.set_fill_color(255, 255, 255)
            self.set_font("Helvetica", "", 9)
            self.cell(col_w[0], 7, gap.title()[:24], border=1, fill=True)

            sev_color = COLORS["danger"] if sev == "High" else COLORS["warning"] if sev == "Medium" else COLORS["muted"]
            self.set_text_color(*sev_color)
            self.cell(col_w[1], 7, sev, border=1, fill=True)
            self.set_text_color(0, 0, 0)
            self.cell(col_w[2], 7, course_name, border=1, fill=True)
            self.cell(col_w[3], 7, platform, border=1, fill=True)
            self.ln()

    def roadmap_section(self, roadmap: str):
        self.set_font("Helvetica", "", 9)
        # Strip markdown and print plain text
        import re
        plain = re.sub(r'#{1,6}\s*', '', roadmap)
        plain = re.sub(r'\*{1,2}([^*]+)\*{1,2}', r'\1', plain)
        plain = re.sub(r'`([^`]+)`', r'\1', plain)
        self.multi_cell(0, 5.5, plain[:4000])

    def salary_section(self, salary: dict, role_title: str):
        current = salary.get("current", {})
        after = salary.get("after_upskilling", {})

        self.set_font("Helvetica", "B", 16)
        self.set_text_color(*COLORS["muted"])
        self.cell(0, 10, f"Role: {role_title}", ln=True)
        self.ln(4)

        self.set_font("Helvetica", "B", 13)
        self.set_text_color(0, 0, 0)
        self.cell(90, 9, "Current Estimated Range", border=1, align="C")
        self.cell(90, 9, "After Closing All Gaps", border=1, align="C")
        self.ln()

        self.set_font("Helvetica", "B", 20)
        self.set_text_color(*COLORS["warning"])
        c_label = current.get("label", "₹5-10 LPA")
        self.cell(90, 16, c_label, border=1, align="C")
        self.set_text_color(*COLORS["success"])
        a_label = after.get("label", "₹10-18 LPA")
        self.cell(90, 16, a_label, border=1, align="C")
        self.ln()
        self.set_text_color(0, 0, 0)
        self.ln(6)

        note = salary.get("note", "Estimates based on 2024 Indian market data.")
        self.set_font("Helvetica", "I", 9)
        self.set_text_color(*COLORS["muted"])
        self.multi_cell(0, 6, f"Note: {note}")

    def course_recommendations(self, retrieved: dict):
        self.set_font("Helvetica", "", 10)
        count = 0
        for skill, courses in retrieved.items():
            if count >= 12:
                break
            if courses:
                c = courses[0]
                self.set_font("Helvetica", "B", 11)
                self.set_text_color(*COLORS["primary"])
                self.cell(0, 8, f"▶  {skill.title()}", ln=True)
                self.set_text_color(0, 0, 0)
                self.set_font("Helvetica", "", 10)
                self.cell(0, 6, f"   {c.get('course_name', '')}", ln=True)
                self.cell(0, 6, f"   Platform: {c.get('platform', '')}  |  Duration: {c.get('duration', '')}  |  {'Free' if c.get('free') else 'Paid'}", ln=True)
                self.set_text_color(*COLORS["primary"])
                self.cell(0, 6, f"   URL: {c.get('url', '')}", ln=True)
                self.set_text_color(0, 0, 0)
                self.ln(3)
                count += 1

    def next_steps(self, analysis: dict):
        steps = [
            "1. Close critical gaps first — spend 70% of study time on High severity gaps.",
            "2. Add the recommended courses to your calendar using the .ics export.",
            "3. Build 1 project per major gap and push to GitHub within the next 30 days.",
            "4. Update your resume with the rewritten sections from the Resume Rewriter tab.",
            "5. Apply the ATS recommendations to increase your shortlist rate.",
            "6. Connect with the suggested mentors on LinkedIn this week.",
            "7. Re-run this analysis every 2 weeks to track your improvement.",
        ]
        self.set_font("Helvetica", "", 11)
        for step in steps:
            self.multi_cell(0, 8, step)
            self.ln(2)

        self.ln(8)
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(*COLORS["primary"])
        self.multi_cell(0, 9,
            "Remember: Every expert was once a beginner. "
            "Close one gap at a time, ship real projects, and stay consistent. "
            "You've got this! 🚀")
